services:
  streamlit-ui:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PYTHON_IMAGE_VERSION=${PYTHON_IMAGE_VERSION}
    volumes:
      - .:/app/
    ports:
      - "${PORT}:${PORT}"
    environment:
      PORT: ${PORT}
    models:
      - llm

models:
  llm:
    model: ${LLM_MODEL_IMAGE}
    context_size: 8192
