services:
  streamlit-ui:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PYTHON_IMAGE_VERSION=${PYTHON_IMAGE_VERSION}
    volumes:
      - .:/app/
    ports:
      - "${PORT}:${PORT}"
    models:
      - llm
    tty: true
    command: ["sleep", "infinity"]

models:
  llm:
    model: ${LLM_MODEL_IMAGE}
    context_size: 8192
    # runtime_flags:
    #   - "--no-stream"
